
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 08 20:05:44 CET 2015
//----------------------------------------------------

package toucan.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int OP = 14;
  public static final int ACCFER = 10;
  public static final int IDF = 13;
  public static final int PARFER = 8;
  public static final int CROFER = 5;
  public static final int POINTVIRGULE = 2;
  public static final int CSTE = 12;
  public static final int ACCOUV = 9;
  public static final int PAROUV = 7;
  public static final int TYPEPRIMITIF = 11;
  public static final int EOF = 0;
  public static final int CROOUV = 4;
  public static final int EGAL = 6;
  public static final int error = 1;
  public static final int TAB = 3;
}

